---
title: 'Supplementary Information: Whose Social Capital?'
author: "jimi adams & Kate Vinita Fitch"
date:  "`r format(Sys.time(), '%Y %B %d')`"
output: pdf_document
bibliography: references.bib
link-citations: true
---

This document provides further details and justification for some of the analytic decisions made in the primary manuscript. We also provide some additional ancillary descriptive characteristics of our analytic corpus and results.^[Code for all analyses can be found at:  https://github.com/jimiadams/SocialCapital-Viz.]

## Network Construction

First, some basic information about the scope of the corpus and constructed networks.

  - Number of papers in corpus: 21,160
  - Total citations: 985,749 (to 533,111 unique papers)
  - Giant component [@Harary:1969] size in citation network: 546,159
      - this drops 4,073 papers from focal corpus
  - Citations in GC: 981,875 (to 529,244 unique papers)

## Identifying Key Papers

Next, here are the identified "key papers" (those receiving >1000 citations from within the corpus; the *least* cited of these is cited by >5% of *all* papers in the corpus) and the umber of citations each received from within the corpus, sorted by number of citations received:

Citation            Cites
--------            -------------
@coleman_1988       4095
@putnam_2000        3594
@putnam_1993        2802
@portes_1998        2289
@granovetter_1973   2157
@nahapiet_1998      2113
@coleman_1990       2097
@bourdieu_1986      2090             
@putnam_1995        1785
@adler_2002         1609
@lin_2001           1220
@burt_1992          1062
--------            -------------- 

Alphabetized:

Citation            Cites
--------            -------------
@adler_2002         1609
@bourdieu_1986      2090             
@burt_1992          1062
@coleman_1990       2097
@coleman_1988       4095
@granovetter_1973   2157
@lin_2001           1220
@nahapiet_1998      2113
@portes_1998        2289
@putnam_2000        3594
@putnam_1995        1785
@putnam_1993        2802
--------            --------------   

Given that two of these papers are not primarily original theorization of the social capital concept, but review papers summarizing its application in particular fields, the prominence of their citations in those fields (and central role in defining 2 of the clusters described in the manuscript itself) provides additional evidence of a pattern of citation "hijacking" by review articles as described by @McMahan_2021. 

## Estimating Community Structure
For conducting the community structure analyses on this citation network, the paper presents results using [@Blondel:2008aa], but we also ran all analyses using [@Clauset2004]. In the summaries in this SI, we include both, and also elaborate the demonstrated similarities and differences between these strategies. After applying the community detection algorithms on the citation giant component, we have: 
  
  - Number of papers in components size>10k
    - louvain solution: 304,163
    - fast-greedy solution: 307,977
    
The modularity-maximized solutions identify 6 (Louvain) and 5 (fast greedy) communities respectively containing >1000 papers in each, and each these provide *clear* cut-points, as is common graph theoretically (e.g., the next largest component in the Louvain solution has 389 papers, while in the fast-greedy solution it contains fewer than 50 papers). Within those components, the largest clusters include respectively (N, %) of the papers from the focal corpus:

**Louvain Solution**

Cluster   Papers        % of Corpus       
--------  ---------     ---------
1         2516            11.9
2         2319            11.0 
3         2212            10.5
4         1514            7.2
5         1449            6.8
6         1210            5.7
Total     11220           53

--------  ---------     ---------

**Fast-Greedy Solution**

Cluster   Papers        % of Corpus       
--------  ---------     ---------
1         3980            18.8
2         3060            14.5 
3         2692            12.7
4         1485            7.0
5         754             3.6
Total     11971           56
--------  ---------     ---------
  
Across these clusters, the key papers collectively receive the following number of citations:^[The paper-specific citations can be found in the top panel of Figure 1 in the manuscript, and the [solution_name]_cites object in the .Rda files in the GitHub repo data folder.]

  - Louvain solution - {7149 4090 3467 3263 3626 3106}
  - fast greedy solution - {9363 8433 4320 3202  933}

## Exploring the *content* of the clusters
To provide some short-hand labels for discussing the results here in a more readily parsimonious way, I finally examined for the citing papers within each of the identified communities the distributions of their (1) journals' ISI subject categories, (2) author provided keywords, and (3) ISI-provided keywords. 

**This warrants an important caveat; these are *not* intended as providing systematic potential accounts of the sources of the differences identified here; that would require more detailed analytic strategies that are beyond the scope of this analysis and paper. These are merely meant to provide heurisitc labels that are more intelligible than arbitrary numeric labels, for ease of discussion in the manuscript.** 

That interpretive caveat having been established, below, we provide the top subject categories and keywords for each of the community solutions, to illustrate how the preliminary labels were generated.

``` {r table}

```
      
## References