---
title: "Whose Social Capital?: Citation and Co-Citation Patterns of a Fragmented Concept"
author: jimi adams & Kate Vinita Fitch
date:  "`r format(Sys.time(), '%Y %B %d')`"
output: html_document
bibliography: references.bib
link-citations: true
---

**Abstract**: Despite its wide use across the social sciences, social capital research has been regularly criticized as having fuzzy conceptualization, resulting in multiple (potentially conflicting) operationalizations. Our analyses employ bibliometric analytic tools to demonstrate the disconnected structure of social capital research. The resulting visualization illustrates one potential source of the confusion surrounding social capital–that there are many, potentially non-overlapping versions of the idea, rather than one unified social capital concept. 


There are few widely used concepts in the social sciences with as much variability in its theorization and operationalization as social capital. In fact, some have argued that “social capital” is used to mean so many different things that it is left without much analytic utility at all [@fine_2002]. We argue that this view throws a particularly promising theoretical baby out with the admittedly murky empirical bathwater. Anyone desiring conceptual clarity when using social capital in their own work–or conveying its utility to others–likely has their own mental map of the social capital concept, and preferred sources for establishing its bases. Often these mappings seem incompatible across their uses. The resulting confusion unnecessarily complicates our understanding of social capital’s potential utility for the social sciences.

Given the highly variable and potentially particularized nature of those conceptualizations, we draw on an emerging set of bibliometric analytic tools to provide systematic means for describing the conceptual terrain represented in the myriad ways social capital has been deployed in the literature.

## The Mess We're in
This visualization examines the bibliometric patterns in the citation and co-citation networks [@yan_2012] of social capital literature, by asking how “key papers” are differentially deployed by scholarship in the field. Specifically, we (1) construct a citation network among papers in a corpus of social capital literature (where each paper "receives" a tie from the papers it cites),^[The direction of the ties in citation networks is intended to reflect the flow of ideas from *cited* papers to *citing* papers.] (2) estimate the **community** structure of that network (“communities” identify sub-segments of the network that are more likely to cite others within their community, and less likely to cite those outside their community), then (3) assess how papers from each of those identified communities deploy the "key papers", as indicated by both: (a) the distribution of **citations** those key papers receive, and (b) their joint usage as indicated by community-level **co-citation** rates (“co-citations” enumerate how frequently papers in the corpus *jointly* cite each pair of papers from the key papers list).

## Data & Approach
Our corpus includes 21,160 publications that: (1) used "social capital" in the title, keywords, or abstract, (2) were in the ISI Web of Science "Core Collection", and (3) were published between 1974-01-01 and 2020-10-31.^[Code for all analyses is available at: https://github.com/jimiadams/SocialCapital-Viz.] These papers receive 0-4,095 citations from other publications within the corpus.^[We focus on citations *within* the corpus rather than total citations received (e.g., as tallied by ISI) to focus on each paper's contributions to *social capital* literature in particular, rather than their broader scientific impact.] From that distribution we identified 12 "key papers" that received more than 1,000 citations (i.e., are each cited by 5-19% of the papers in the analyzed corpus).^[We also explored other cut-points, but this sufficiently captured the set of disproportionately cited papers in the corpus.] 

Next, we identify the community structure of the citation network among our full corpus.^[We report results using [@Blondel:2008aa], but also ran similar analyses using [@Clauset2004], with similar conclusions if not identical results.] We then asked (1) how many citations each of the identified key papers received from papers within each community (see the histograms at the top of each figure panel), and (2) how frequently combinations of those key papers were jointly cited by other papers within each community (see the tile plots at the bottom of each figure panel).^[The latter is presented as Z-scores to emphasize the independent differences in the co-citation rates, so as to not simply reproduce the differences in citation counts via a second metric.] In combination, these serve to illustrate how different communities within the social capital literature differentially: (1) evaluate the importance of the set of key papers, and (2) see the ideas of those key papers as related to one another.

![**Figure 1. Key Paper (Co-)Citation Patterns by Citation Community.** The top part of each panel presents the frequency of citations received by each of the identified key papers. The bottom part of each panel presents how frequently pairs of papers are co-cited by others. Each panel represents these patterns separately for the network communities that were identified from the citation network. Coloring denotes combinations that are more (blue) or less (red) common than expected, given the marginal distribution of citations received in the full corpus.](img/Figure1.png)

## Does this Help Make Sense of Social Capital?
Is social capital a unified concept, or do we have so many conceptualizations, operationalizations, and uses of "social capital" because the authors using the term are fragmented into different communities who each see "social capital" through different---potentially incompatible---lenses? 

The evidence presented in Figure 1 suggests that some communities draw on the key papers in similar patterns (e.g., see the similarities in both panels between clusters 2 and 3), and what differentiates them arises instead because of the citation differences in how they use literature *other* than social capital (likely arising from differential substantive foci between those clusters). 

However other clusters demonstrate patterns that substantially differ from one another. The first cluster is dominated by a handful of the key citations (Adler and Kwon 2002; Burt 1992; Coleman 1988; and especially Nahapiet & Ghoshal 1998), whereas other clusters seem to be dominated by a single key citation (Coleman 1988 in cluster 4 and Putnam 2000 in cluster 5). Moreover, some clusters also are substantially different from others in the key citations co-cited with others at significantly lower levels (e.g., cluster 4 papers tend to use a limited number of the key citations per paper, leading to dramatically infrequent co-citation rates of the key papers within this cluster). Clusters 1, 5, and 6 appear to be relatively ecumenical in the combinations of papers that they jointly draw upon to cite social capital ideas. In contrast, while both Coleman (1988) and Putnam (2000) are relatively common citations within Cluster 4 (see 5th and 10th bars in the top of panel 4), they are significantly unlikely to be cited *together* within that cluster (see red cell between cited papers 5 and 10 in the bottom of that panel).
 
This visualization provides initial evidence that there is not a single unified concept of "social capital" as indicated by citation patterns. Instead there appear to be multiple "social capital" concepts in the literature, and those are differentially drawn upon by researchers in somewhat disconnected communities. This suggests future research may want to account for how and why those differences arise, and whether there are sub-dimensions of social capital as an analytic concept that underpin these potentially substantial differences.

## References